using Yeluru_Sai_HW6.Models;
using Yeluru_Sai_HW6.DAL;
using System.Data.Entity.Migrations;
using System.Linq;

namespace Yeluru_Sai_HW6.Migrations
{
	public static class AddCustomers
	{
		public static AppDbContext db = new AppDbContext();

        public static void AddFrequencies()
        {
            //Create new frequencies
            Frequency f1 = new Frequency();
            f1.Name = "Daily";
            db.Frequencies.AddOrUpdate(f => f.Name, f1);

            Frequency f2 = new Frequency();
            f2.Name = "Monthly";
            db.Frequencies.AddOrUpdate(f => f.Name, f2);

            Frequency f3 = new Frequency();
            f3.Name = "Never";
            db.Frequencies.AddOrUpdate(f => f.Name, f3);

            Frequency f4 = new Frequency();
            f4.Name = "Often";
            db.Frequencies.AddOrUpdate(f => f.Name, f4);

            Frequency f5 = new Frequency();
            f5.Name = "Once";
            db.Frequencies.AddOrUpdate(f => f.Name, f5);

            Frequency f6 = new Frequency();
            f6.Name = "Seldom";
            db.Frequencies.AddOrUpdate(f => f.Name, f6);

            Frequency f7 = new Frequency();
            f7.Name = "Weekly";
            db.Frequencies.AddOrUpdate(f => f.Name, f7);

            Frequency f8 = new Frequency();
            f8.Name = "Yearly";
            db.Frequencies.AddOrUpdate(f => f.Name, f8);

            Frequency f9 = new Frequency();
            f9.Name = "Not used";
            db.Frequencies.AddOrUpdate(f => f.Name, f9);

            //update database
            db.SaveChanges();
        }

        public static void SeedCustomers()
		{
			Customer c1 = new Customer();
			c1.FirstName = "Donald";
			c1.LastName = "Crawford";
			c1.Gender = "Male";
			c1.Email = "dcrawford0@vimeo.com";
			c1.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Often");
			c1.ReferredFrom = "cnet.com";
			c1.AverageSale = 544.9m;
			db.Customers.AddOrUpdate(c => c.Email, c1);
			db.SaveChanges();

			Customer c2 = new Customer();
			c2.FirstName = "Gary";
			c2.LastName = "Phillips";
			c2.Gender = "Male";
			c2.Email = "gphillips1@fastcompany.com";
			c2.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Seldom");
			c2.ReferredFrom = "nba.com";
			c2.AverageSale = 212.26m;
			db.Customers.AddOrUpdate(c => c.Email, c2);
			db.SaveChanges();

			Customer c3 = new Customer();
			c3.FirstName = "Robin";
			c3.LastName = "Matthews";
			c3.Gender = "Female";
			c3.Email = "rmatthews2@meetup.com";
			c3.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Seldom");
			c3.ReferredFrom = "howstuffworks.com";
			c3.AverageSale = 336.2m;
			db.Customers.AddOrUpdate(c => c.Email, c3);
			db.SaveChanges();

			Customer c4 = new Customer();
			c4.FirstName = "Cheryl";
			c4.LastName = "Alvarez";
			c4.Gender = "Female";
			c4.Email = "calvarez3@dagondesign.com";
			c4.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Never");
			c4.ReferredFrom = "mapy.cz";
			c4.AverageSale = 472.29m;
			db.Customers.AddOrUpdate(c => c.Email, c4);
			db.SaveChanges();

			Customer c5 = new Customer();
			c5.FirstName = "Kathleen";
			c5.LastName = "Dean";
			c5.Gender = "Female";
			c5.Email = "kdean4@bloglines.com";
			c5.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Once");
			c5.ReferredFrom = "slashdot.org";
			c5.AverageSale = 451.1m;
			db.Customers.AddOrUpdate(c => c.Email, c5);
			db.SaveChanges();

			Customer c6 = new Customer();
			c6.FirstName = "Julie";
			c6.LastName = "Howell";
			c6.Gender = "Female";
			c6.Email = "jhowell5@bizjournals.com";
			c6.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Daily");
			c6.ReferredFrom = "sun.com";
			c6.AverageSale = 396.86m;
			db.Customers.AddOrUpdate(c => c.Email, c6);
			db.SaveChanges();

			Customer c7 = new Customer();
			c7.FirstName = "Mary";
			c7.LastName = "Martin";
			c7.Gender = "Female";
			c7.Email = "mmartin6@virginia.edu";
			c7.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Often");
			c7.ReferredFrom = "fc2.com";
			c7.AverageSale = 446.05m;
			db.Customers.AddOrUpdate(c => c.Email, c7);
			db.SaveChanges();

			Customer c8 = new Customer();
			c8.FirstName = "Richard";
			c8.LastName = "Duncan";
			c8.Gender = "Male";
			c8.Email = "rduncan7@sfgate.com";
			c8.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Yearly");
			c8.ReferredFrom = "nbcnews.com";
			c8.AverageSale = 574.44m;
			db.Customers.AddOrUpdate(c => c.Email, c8);
			db.SaveChanges();

			Customer c9 = new Customer();
			c9.FirstName = "Jessica";
			c9.LastName = "King";
			c9.Gender = "Female";
			c9.Email = "jking8@e-recht24.de";
			c9.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Weekly");
			c9.ReferredFrom = "webs.com";
			c9.AverageSale = 296.2m;
			db.Customers.AddOrUpdate(c => c.Email, c9);
			db.SaveChanges();

			Customer c10 = new Customer();
			c10.FirstName = "Dennis";
			c10.LastName = "Morgan";
			c10.Gender = "Male";
			c10.Email = "dmorgan9@flickr.com";
			c10.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Yearly");
			c10.ReferredFrom = "discovery.com";
			c10.AverageSale = 347.69m;
			db.Customers.AddOrUpdate(c => c.Email, c10);
			db.SaveChanges();

			Customer c11 = new Customer();
			c11.FirstName = "Jane";
			c11.LastName = "Carpenter";
			c11.Gender = "Female";
			c11.Email = "jcarpentera@chron.com";
			c11.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Never");
			c11.ReferredFrom = "upenn.edu";
			c11.AverageSale = 525.34m;
			db.Customers.AddOrUpdate(c => c.Email, c11);
			db.SaveChanges();

			Customer c12 = new Customer();
			c12.FirstName = "Margaret";
			c12.LastName = "Kelly";
			c12.Gender = "Female";
			c12.Email = "mkellyb@mayoclinic.com";
			c12.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Daily");
			c12.ReferredFrom = "themeforest.net";
			c12.AverageSale = 340.81m;
			db.Customers.AddOrUpdate(c => c.Email, c12);
			db.SaveChanges();

			Customer c13 = new Customer();
			c13.FirstName = "Russell";
			c13.LastName = "Cox";
			c13.Gender = "Male";
			c13.Email = "rcoxc@is.gd";
			c13.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Often");
			c13.ReferredFrom = "virginia.edu";
			c13.AverageSale = 500.66m;
			db.Customers.AddOrUpdate(c => c.Email, c13);
			db.SaveChanges();

			Customer c14 = new Customer();
			c14.FirstName = "Sarah";
			c14.LastName = "Harper";
			c14.Gender = "Female";
			c14.Email = "sharperd@hatena.ne.jp";
			c14.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Yearly");
			c14.ReferredFrom = "usgs.gov";
			c14.AverageSale = 450.21m;
			db.Customers.AddOrUpdate(c => c.Email, c14);
			db.SaveChanges();

			Customer c15 = new Customer();
			c15.FirstName = "Robin";
			c15.LastName = "Rogers";
			c15.Gender = "Female";
			c15.Email = "rrogerse@oracle.com";
			c15.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Never");
			c15.ReferredFrom = "columbia.edu";
			c15.AverageSale = 336.17m;
			db.Customers.AddOrUpdate(c => c.Email, c15);
			db.SaveChanges();

			Customer c16 = new Customer();
			c16.FirstName = "Todd";
			c16.LastName = "Lee";
			c16.Gender = "Male";
			c16.Email = "tleef@home.pl";
			c16.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Weekly");
			c16.ReferredFrom = "nhs.uk";
			c16.AverageSale = 448.92m;
			db.Customers.AddOrUpdate(c => c.Email, c16);
			db.SaveChanges();

			Customer c17 = new Customer();
			c17.FirstName = "Harold";
			c17.LastName = "Stanley";
			c17.Gender = "Male";
			c17.Email = "hstanleyg@mapquest.com";
			c17.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Daily");
			c17.ReferredFrom = "blogspot.com";
			c17.AverageSale = 285.45m;
			db.Customers.AddOrUpdate(c => c.Email, c17);
			db.SaveChanges();

			Customer c18 = new Customer();
			c18.FirstName = "Kelly";
			c18.LastName = "Reynolds";
			c18.Gender = "Female";
			c18.Email = "kreynoldsh@webnode.com";
			c18.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Often");
			c18.ReferredFrom = "google.ru";
			c18.AverageSale = 285.36m;
			db.Customers.AddOrUpdate(c => c.Email, c18);
			db.SaveChanges();

			Customer c19 = new Customer();
			c19.FirstName = "William";
			c19.LastName = "Boyd";
			c19.Gender = "Male";
			c19.Email = "wboydi@arizona.edu";
			c19.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Often");
			c19.ReferredFrom = "list-manage.com";
			c19.AverageSale = 603.65m;
			db.Customers.AddOrUpdate(c => c.Email, c19);
			db.SaveChanges();

			Customer c20 = new Customer();
			c20.FirstName = "Ann";
			c20.LastName = "Sullivan";
			c20.Gender = "Female";
			c20.Email = "asullivanj@accuweather.com";
			c20.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Never");
			c20.ReferredFrom = "theglobeandmail.com";
			c20.AverageSale = 494.37m;
			db.Customers.AddOrUpdate(c => c.Email, c20);
			db.SaveChanges();

			Customer c21 = new Customer();
			c21.FirstName = "Janice";
			c21.LastName = "Henry";
			c21.Gender = "Female";
			c21.Email = "jhenryk@canalblog.com";
			c21.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Daily");
			c21.ReferredFrom = "woothemes.com";
			c21.AverageSale = 266.97m;
			db.Customers.AddOrUpdate(c => c.Email, c21);
			db.SaveChanges();

			Customer c22 = new Customer();
			c22.FirstName = "Matthew";
			c22.LastName = "Bradley";
			c22.Gender = "Male";
			c22.Email = "mbradleyl@vistaprint.com";
			c22.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Weekly");
			c22.ReferredFrom = "pen.io";
			c22.AverageSale = 321.04m;
			db.Customers.AddOrUpdate(c => c.Email, c22);
			db.SaveChanges();

			Customer c23 = new Customer();
			c23.FirstName = "William";
			c23.LastName = "Simpson";
			c23.Gender = "Male";
			c23.Email = "wsimpsonm@cnbc.com";
			c23.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Monthly");
			c23.ReferredFrom = "soundcloud.com";
			c23.AverageSale = 414.18m;
			db.Customers.AddOrUpdate(c => c.Email, c23);
			db.SaveChanges();

			Customer c24 = new Customer();
			c24.FirstName = "Jason";
			c24.LastName = "Alexander";
			c24.Gender = "Male";
			c24.Email = "jalexandern@ebay.co.uk";
			c24.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Never");
			c24.ReferredFrom = "comsenz.com";
			c24.AverageSale = 580.07m;
			db.Customers.AddOrUpdate(c => c.Email, c24);
			db.SaveChanges();

			Customer c25 = new Customer();
			c25.FirstName = "Barbara";
			c25.LastName = "Medina";
			c25.Gender = "Female";
			c25.Email = "bmedinao@auda.org.au";
			c25.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Monthly");
			c25.ReferredFrom = "hud.gov";
			c25.AverageSale = 170.2m;
			db.Customers.AddOrUpdate(c => c.Email, c25);
			db.SaveChanges();

			Customer c26 = new Customer();
			c26.FirstName = "Sharon";
			c26.LastName = "Howell";
			c26.Gender = "Female";
			c26.Email = "showellp@deviantart.com";
			c26.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Monthly");
			c26.ReferredFrom = "tiny.cc";
			c26.AverageSale = 438.33m;
			db.Customers.AddOrUpdate(c => c.Email, c26);
			db.SaveChanges();

			Customer c27 = new Customer();
			c27.FirstName = "Diana";
			c27.LastName = "Moore";
			c27.Gender = "Female";
			c27.Email = "dmooreq@oakley.com";
			c27.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Daily");
			c27.ReferredFrom = "ucla.edu";
			c27.AverageSale = 587.37m;
			db.Customers.AddOrUpdate(c => c.Email, c27);
			db.SaveChanges();

			Customer c28 = new Customer();
			c28.FirstName = "Susan";
			c28.LastName = "Medina";
			c28.Gender = "Female";
			c28.Email = "smedinar@howstuffworks.com";
			c28.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Weekly");
			c28.ReferredFrom = "examiner.com";
			c28.AverageSale = 226.62m;
			db.Customers.AddOrUpdate(c => c.Email, c28);
			db.SaveChanges();

			Customer c29 = new Customer();
			c29.FirstName = "Christina";
			c29.LastName = "Williamson";
			c29.Gender = "Female";
			c29.Email = "cwilliamsons@stumbleupon.com";
			c29.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Never");
			c29.ReferredFrom = "about.com";
			c29.AverageSale = 411.61m;
			db.Customers.AddOrUpdate(c => c.Email, c29);
			db.SaveChanges();

			Customer c30 = new Customer();
			c30.FirstName = "Amanda";
			c30.LastName = "Scott";
			c30.Gender = "Female";
			c30.Email = "ascottt@cafepress.com";
			c30.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Seldom");
			c30.ReferredFrom = "networksolutions.com";
			c30.AverageSale = 372.89m;
			db.Customers.AddOrUpdate(c => c.Email, c30);
			db.SaveChanges();

			Customer c31 = new Customer();
			c31.FirstName = "Edward";
			c31.LastName = "Dixon";
			c31.Gender = "Male";
			c31.Email = "edixonu@wix.com";
			c31.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Weekly");
			c31.ReferredFrom = "marriott.com";
			c31.AverageSale = 487.9m;
			db.Customers.AddOrUpdate(c => c.Email, c31);
			db.SaveChanges();

			Customer c32 = new Customer();
			c32.FirstName = "Emily";
			c32.LastName = "Schmidt";
			c32.Gender = "Female";
			c32.Email = "eschmidtv@sina.com.cn";
			c32.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Seldom");
			c32.ReferredFrom = "google.ru";
			c32.AverageSale = 399.55m;
			db.Customers.AddOrUpdate(c => c.Email, c32);
			db.SaveChanges();

			Customer c33 = new Customer();
			c33.FirstName = "Nicole";
			c33.LastName = "Garrett";
			c33.Gender = "Female";
			c33.Email = "ngarrettw@nba.com";
			c33.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Never");
			c33.ReferredFrom = "oakley.com";
			c33.AverageSale = 399.55m;
			db.Customers.AddOrUpdate(c => c.Email, c33);
			db.SaveChanges();

			Customer c34 = new Customer();
			c34.FirstName = "Henry";
			c34.LastName = "Knight";
			c34.Gender = "Male";
			c34.Email = "hknightx@zimbio.com";
			c34.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Seldom");
			c34.ReferredFrom = "gnu.org";
			c34.AverageSale = 340.85m;
			db.Customers.AddOrUpdate(c => c.Email, c34);
			db.SaveChanges();

			Customer c35 = new Customer();
			c35.FirstName = "Harry";
			c35.LastName = "Evans";
			c35.Gender = "Male";
			c35.Email = "hevansy@g.co";
			c35.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Monthly");
			c35.ReferredFrom = "usgs.gov";
			c35.AverageSale = 418.76m;
			db.Customers.AddOrUpdate(c => c.Email, c35);
			db.SaveChanges();

			Customer c36 = new Customer();
			c36.FirstName = "Robin";
			c36.LastName = "Gray";
			c36.Gender = "Female";
			c36.Email = "rgrayz@storify.com";
			c36.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Seldom");
			c36.ReferredFrom = "cisco.com";
			c36.AverageSale = 400.7m;
			db.Customers.AddOrUpdate(c => c.Email, c36);
			db.SaveChanges();

			Customer c37 = new Customer();
			c37.FirstName = "Carol";
			c37.LastName = "Wallace";
			c37.Gender = "Female";
			c37.Email = "cwallace10@smugmug.com";
			c37.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Often");
			c37.ReferredFrom = "cyberchimps.com";
			c37.AverageSale = 296.89m;
			db.Customers.AddOrUpdate(c => c.Email, c37);
			db.SaveChanges();

			Customer c38 = new Customer();
			c38.FirstName = "Diane";
			c38.LastName = "Miller";
			c38.Gender = "Female";
			c38.Email = "dmiller11@ed.gov";
			c38.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Monthly");
			c38.ReferredFrom = "slate.com";
			c38.AverageSale = 644.72m;
			db.Customers.AddOrUpdate(c => c.Email, c38);
			db.SaveChanges();

			Customer c39 = new Customer();
			c39.FirstName = "Ernest";
			c39.LastName = "Warren";
			c39.Gender = "Male";
			c39.Email = "ewarren12@twitpic.com";
			c39.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Seldom");
			c39.ReferredFrom = "dot.gov";
			c39.AverageSale = 257.09m;
			db.Customers.AddOrUpdate(c => c.Email, c39);
			db.SaveChanges();

			Customer c40 = new Customer();
			c40.FirstName = "Judy";
			c40.LastName = "Wells";
			c40.Gender = "Female";
			c40.Email = "jwells13@xinhuanet.com";
			c40.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Often");
			c40.ReferredFrom = "microsoft.com";
			c40.AverageSale = 211.65m;
			db.Customers.AddOrUpdate(c => c.Email, c40);
			db.SaveChanges();

			Customer c41 = new Customer();
			c41.FirstName = "Alice";
			c41.LastName = "Ramos";
			c41.Gender = "Female";
			c41.Email = "aramos14@youku.com";
			c41.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Yearly");
			c41.ReferredFrom = "deliciousdays.com";
			c41.AverageSale = 462.22m;
			db.Customers.AddOrUpdate(c => c.Email, c41);
			db.SaveChanges();

			Customer c42 = new Customer();
			c42.FirstName = "Louise";
			c42.LastName = "Henry";
			c42.Gender = "Female";
			c42.Email = "lhenry15@icq.com";
			c42.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Often");
			c42.ReferredFrom = "parallels.com";
			c42.AverageSale = 341.7m;
			db.Customers.AddOrUpdate(c => c.Email, c42);
			db.SaveChanges();

			Customer c43 = new Customer();
			c43.FirstName = "Debra";
			c43.LastName = "Wheeler";
			c43.Gender = "Female";
			c43.Email = "dwheeler16@washingtonpost.com";
			c43.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Never");
			c43.ReferredFrom = "wunderground.com";
			c43.AverageSale = 567.94m;
			db.Customers.AddOrUpdate(c => c.Email, c43);
			db.SaveChanges();

			Customer c44 = new Customer();
			c44.FirstName = "Samuel";
			c44.LastName = "Lane";
			c44.Gender = "Male";
			c44.Email = "slane17@imdb.com";
			c44.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Often");
			c44.ReferredFrom = "pen.io";
			c44.AverageSale = 529.99m;
			db.Customers.AddOrUpdate(c => c.Email, c44);
			db.SaveChanges();

			Customer c45 = new Customer();
			c45.FirstName = "Jonathan";
			c45.LastName = "Wells";
			c45.Gender = "Male";
			c45.Email = "jwells18@nymag.com";
			c45.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Once");
			c45.ReferredFrom = "bing.com";
			c45.AverageSale = 486.54m;
			db.Customers.AddOrUpdate(c => c.Email, c45);
			db.SaveChanges();

			Customer c46 = new Customer();
			c46.FirstName = "Harold";
			c46.LastName = "Little";
			c46.Gender = "Male";
			c46.Email = "hlittle19@infoseek.co.jp";
			c46.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Daily");
			c46.ReferredFrom = "forbes.com";
			c46.AverageSale = 581.14m;
			db.Customers.AddOrUpdate(c => c.Email, c46);
			db.SaveChanges();

			Customer c47 = new Customer();
			c47.FirstName = "Jessica";
			c47.LastName = "Jordan";
			c47.Gender = "Female";
			c47.Email = "jjordan1a@imageshack.us";
			c47.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Yearly");
			c47.ReferredFrom = "livejournal.com";
			c47.AverageSale = 316.9m;
			db.Customers.AddOrUpdate(c => c.Email, c47);
			db.SaveChanges();

			Customer c48 = new Customer();
			c48.FirstName = "Lori";
			c48.LastName = "Porter";
			c48.Gender = "Female";
			c48.Email = "lporter1b@oakley.com";
			c48.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Seldom");
			c48.ReferredFrom = "utexas.edu";
			c48.AverageSale = 438.35m;
			db.Customers.AddOrUpdate(c => c.Email, c48);
			db.SaveChanges();

			Customer c49 = new Customer();
			c49.FirstName = "Victor";
			c49.LastName = "Palmer";
			c49.Gender = "Male";
			c49.Email = "vpalmer1c@spiegel.de";
			c49.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Yearly");
			c49.ReferredFrom = "omniture.com";
			c49.AverageSale = 214.37m;
			db.Customers.AddOrUpdate(c => c.Email, c49);
			db.SaveChanges();

			Customer c50 = new Customer();
			c50.FirstName = "Anthony";
			c50.LastName = "Cooper";
			c50.Gender = "Male";
			c50.Email = "acooper1d@histats.com";
			c50.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Often");
			c50.ReferredFrom = "technorati.com";
			c50.AverageSale = 350.05m;
			db.Customers.AddOrUpdate(c => c.Email, c50);
			db.SaveChanges();

			Customer c51 = new Customer();
			c51.FirstName = "Alice";
			c51.LastName = "Harper";
			c51.Gender = "Female";
			c51.Email = "aharper1e@constantcontact.com";
			c51.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Monthly");
			c51.ReferredFrom = "blogger.com";
			c51.AverageSale = 505.32m;
			db.Customers.AddOrUpdate(c => c.Email, c51);
			db.SaveChanges();

			Customer c52 = new Customer();
			c52.FirstName = "Steve";
			c52.LastName = "Dixon";
			c52.Gender = "Male";
			c52.Email = "sdixon1f@oakley.com";
			c52.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Weekly");
			c52.ReferredFrom = "tinyurl.com";
			c52.AverageSale = 406.82m;
			db.Customers.AddOrUpdate(c => c.Email, c52);
			db.SaveChanges();

			Customer c53 = new Customer();
			c53.FirstName = "Benjamin";
			c53.LastName = "Mason";
			c53.Gender = "Male";
			c53.Email = "bmason1g@npr.org";
			c53.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Seldom");
			c53.ReferredFrom = "sciencedaily.com";
			c53.AverageSale = 465.25m;
			db.Customers.AddOrUpdate(c => c.Email, c53);
			db.SaveChanges();

			Customer c54 = new Customer();
			c54.FirstName = "Karen";
			c54.LastName = "Watkins";
			c54.Gender = "Female";
			c54.Email = "kwatkins1h@theguardian.com";
			c54.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Yearly");
			c54.ReferredFrom = "so-net.ne.jp";
			c54.AverageSale = 501.93m;
			db.Customers.AddOrUpdate(c => c.Email, c54);
			db.SaveChanges();

			Customer c55 = new Customer();
			c55.FirstName = "Julia";
			c55.LastName = "Harris";
			c55.Gender = "Female";
			c55.Email = "jharris1i@smugmug.com";
			c55.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Weekly");
			c55.ReferredFrom = "digg.com";
			c55.AverageSale = 497.45m;
			db.Customers.AddOrUpdate(c => c.Email, c55);
			db.SaveChanges();

			Customer c56 = new Customer();
			c56.FirstName = "Edward";
			c56.LastName = "Ruiz";
			c56.Gender = "Male";
			c56.Email = "eruiz1j@flickr.com";
			c56.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Weekly");
			c56.ReferredFrom = "psu.edu";
			c56.AverageSale = 396.38m;
			db.Customers.AddOrUpdate(c => c.Email, c56);
			db.SaveChanges();

			Customer c57 = new Customer();
			c57.FirstName = "Carolyn";
			c57.LastName = "Carroll";
			c57.Gender = "Female";
			c57.Email = "ccarroll1k@furl.net";
			c57.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Yearly");
			c57.ReferredFrom = "odnoklassniki.ru";
			c57.AverageSale = 354.78m;
			db.Customers.AddOrUpdate(c => c.Email, c57);
			db.SaveChanges();

			Customer c58 = new Customer();
			c58.FirstName = "George";
			c58.LastName = "Alvarez";
			c58.Gender = "Male";
			c58.Email = "galvarez1l@skype.com";
			c58.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Monthly");
			c58.ReferredFrom = "liveinternet.ru";
			c58.AverageSale = 407.22m;
			db.Customers.AddOrUpdate(c => c.Email, c58);
			db.SaveChanges();

			Customer c59 = new Customer();
			c59.FirstName = "Brandon";
			c59.LastName = "Roberts";
			c59.Gender = "Male";
			c59.Email = "broberts1m@topsy.com";
			c59.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Monthly");
			c59.ReferredFrom = "usa.gov";
			c59.AverageSale = 438.99m;
			db.Customers.AddOrUpdate(c => c.Email, c59);
			db.SaveChanges();

			Customer c60 = new Customer();
			c60.FirstName = "Raymond";
			c60.LastName = "Webb";
			c60.Gender = "Male";
			c60.Email = "rwebb1n@printfriendly.com";
			c60.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Daily");
			c60.ReferredFrom = "msu.edu";
			c60.AverageSale = 516.72m;
			db.Customers.AddOrUpdate(c => c.Email, c60);
			db.SaveChanges();

			Customer c61 = new Customer();
			c61.FirstName = "Lillian";
			c61.LastName = "Schmidt";
			c61.Gender = "Female";
			c61.Email = "lschmidt1o@parallels.com";
			c61.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Daily");
			c61.ReferredFrom = "1688.com";
			c61.AverageSale = 581.53m;
			db.Customers.AddOrUpdate(c => c.Email, c61);
			db.SaveChanges();

			Customer c62 = new Customer();
			c62.FirstName = "Margaret";
			c62.LastName = "Jacobs";
			c62.Gender = "Female";
			c62.Email = "mjacobs1p@amazon.co.uk";
			c62.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Seldom");
			c62.ReferredFrom = "reference.com";
			c62.AverageSale = 326.73m;
			db.Customers.AddOrUpdate(c => c.Email, c62);
			db.SaveChanges();

			Customer c63 = new Customer();
			c63.FirstName = "Beverly";
			c63.LastName = "Carr";
			c63.Gender = "Female";
			c63.Email = "bcarr1q@reverbnation.com";
			c63.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Once");
			c63.ReferredFrom = "sogou.com";
			c63.AverageSale = 574.97m;
			db.Customers.AddOrUpdate(c => c.Email, c63);
			db.SaveChanges();

			Customer c64 = new Customer();
			c64.FirstName = "Adam";
			c64.LastName = "Phillips";
			c64.Gender = "Male";
			c64.Email = "aphillips1r@4shared.com";
			c64.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Once");
			c64.ReferredFrom = "tinypic.com";
			c64.AverageSale = 457.5m;
			db.Customers.AddOrUpdate(c => c.Email, c64);
			db.SaveChanges();

			Customer c65 = new Customer();
			c65.FirstName = "Amy";
			c65.LastName = "Mccoy";
			c65.Gender = "Female";
			c65.Email = "amccoy1s@disqus.com";
			c65.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Daily");
			c65.ReferredFrom = "yahoo.co.jp";
			c65.AverageSale = 338.65m;
			db.Customers.AddOrUpdate(c => c.Email, c65);
			db.SaveChanges();

			Customer c66 = new Customer();
			c66.FirstName = "Adam";
			c66.LastName = "Bennett";
			c66.Gender = "Male";
			c66.Email = "abennett1t@over-blog.com";
			c66.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Daily");
			c66.ReferredFrom = "google.com.au";
			c66.AverageSale = 438.75m;
			db.Customers.AddOrUpdate(c => c.Email, c66);
			db.SaveChanges();

			Customer c67 = new Customer();
			c67.FirstName = "Raymond";
			c67.LastName = "Jacobs";
			c67.Gender = "Male";
			c67.Email = "rjacobs1u@toplist.cz";
			c67.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Yearly");
			c67.ReferredFrom = "ucla.edu";
			c67.AverageSale = 511.87m;
			db.Customers.AddOrUpdate(c => c.Email, c67);
			db.SaveChanges();

			Customer c68 = new Customer();
			c68.FirstName = "Amanda";
			c68.LastName = "Spencer";
			c68.Gender = "Female";
			c68.Email = "aspencer1v@yale.edu";
			c68.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Seldom");
			c68.ReferredFrom = "amazon.co.jp";
			c68.AverageSale = 283.11m;
			db.Customers.AddOrUpdate(c => c.Email, c68);
			db.SaveChanges();

			Customer c69 = new Customer();
			c69.FirstName = "Shawn";
			c69.LastName = "Perry";
			c69.Gender = "Male";
			c69.Email = "sperry1w@lycos.com";
			c69.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Yearly");
			c69.ReferredFrom = "ifeng.com";
			c69.AverageSale = 353.6m;
			db.Customers.AddOrUpdate(c => c.Email, c69);
			db.SaveChanges();

			Customer c70 = new Customer();
			c70.FirstName = "Daniel";
			c70.LastName = "Castillo";
			c70.Gender = "Male";
			c70.Email = "dcastillo1x@exblog.jp";
			c70.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Seldom");
			c70.ReferredFrom = "sina.com.cn";
			c70.AverageSale = 315.11m;
			db.Customers.AddOrUpdate(c => c.Email, c70);
			db.SaveChanges();

			Customer c71 = new Customer();
			c71.FirstName = "Joe";
			c71.LastName = "Johnston";
			c71.Gender = "Male";
			c71.Email = "jjohnston1y@aol.com";
			c71.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Monthly");
			c71.ReferredFrom = "google.ca";
			c71.AverageSale = 369.09m;
			db.Customers.AddOrUpdate(c => c.Email, c71);
			db.SaveChanges();

			Customer c72 = new Customer();
			c72.FirstName = "Alice";
			c72.LastName = "Perkins";
			c72.Gender = "Female";
			c72.Email = "aperkins1z@rediff.com";
			c72.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Seldom");
			c72.ReferredFrom = "wiley.com";
			c72.AverageSale = 378.54m;
			db.Customers.AddOrUpdate(c => c.Email, c72);
			db.SaveChanges();

			Customer c73 = new Customer();
			c73.FirstName = "Rachel";
			c73.LastName = "Stevens";
			c73.Gender = "Female";
			c73.Email = "rstevens20@xinhuanet.com";
			c73.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Once");
			c73.ReferredFrom = "seattletimes.com";
			c73.AverageSale = 573.05m;
			db.Customers.AddOrUpdate(c => c.Email, c73);
			db.SaveChanges();

			Customer c74 = new Customer();
			c74.FirstName = "Eugene";
			c74.LastName = "Peterson";
			c74.Gender = "Male";
			c74.Email = "epeterson21@opera.com";
			c74.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Daily");
			c74.ReferredFrom = "harvard.edu";
			c74.AverageSale = 468.61m;
			db.Customers.AddOrUpdate(c => c.Email, c74);
			db.SaveChanges();

			Customer c75 = new Customer();
			c75.FirstName = "Jean";
			c75.LastName = "Davis";
			c75.Gender = "Female";
			c75.Email = "jdavis22@ning.com";
			c75.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Weekly");
			c75.ReferredFrom = "symantec.com";
			c75.AverageSale = 458.11m;
			db.Customers.AddOrUpdate(c => c.Email, c75);
			db.SaveChanges();

			Customer c76 = new Customer();
			c76.FirstName = "Justin";
			c76.LastName = "Boyd";
			c76.Gender = "Male";
			c76.Email = "jboyd23@reference.com";
			c76.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Weekly");
			c76.ReferredFrom = "blinklist.com";
			c76.AverageSale = 384.79m;
			db.Customers.AddOrUpdate(c => c.Email, c76);
			db.SaveChanges();

			Customer c77 = new Customer();
			c77.FirstName = "Roger";
			c77.LastName = "Nelson";
			c77.Gender = "Male";
			c77.Email = "rnelson24@technorati.com";
			c77.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Once");
			c77.ReferredFrom = "e-recht24.de";
			c77.AverageSale = 572.79m;
			db.Customers.AddOrUpdate(c => c.Email, c77);
			db.SaveChanges();

			Customer c78 = new Customer();
			c78.FirstName = "Matthew";
			c78.LastName = "Gonzalez";
			c78.Gender = "Male";
			c78.Email = "mgonzalez25@ucsd.edu";
			c78.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Daily");
			c78.ReferredFrom = "accuweather.com";
			c78.AverageSale = 404.88m;
			db.Customers.AddOrUpdate(c => c.Email, c78);
			db.SaveChanges();

			Customer c79 = new Customer();
			c79.FirstName = "Eric";
			c79.LastName = "Baker";
			c79.Gender = "Male";
			c79.Email = "ebaker26@microsoft.com";
			c79.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Monthly");
			c79.ReferredFrom = "dagondesign.com";
			c79.AverageSale = 583.94m;
			db.Customers.AddOrUpdate(c => c.Email, c79);
			db.SaveChanges();

			Customer c80 = new Customer();
			c80.FirstName = "Lisa";
			c80.LastName = "Freeman";
			c80.Gender = "Female";
			c80.Email = "lfreeman27@odnoklassniki.ru";
			c80.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Weekly");
			c80.ReferredFrom = "youtube.com";
			c80.AverageSale = 470.43m;
			db.Customers.AddOrUpdate(c => c.Email, c80);
			db.SaveChanges();

			Customer c81 = new Customer();
			c81.FirstName = "Sara";
			c81.LastName = "Myers";
			c81.Gender = "Female";
			c81.Email = "smyers28@marketwatch.com";
			c81.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Never");
			c81.ReferredFrom = "scribd.com";
			c81.AverageSale = 327.46m;
			db.Customers.AddOrUpdate(c => c.Email, c81);
			db.SaveChanges();

			Customer c82 = new Customer();
			c82.FirstName = "Jeremy";
			c82.LastName = "Griffin";
			c82.Gender = "Male";
			c82.Email = "jgriffin29@marketwatch.com";
			c82.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Never");
			c82.ReferredFrom = "comcast.net";
			c82.AverageSale = 466.38m;
			db.Customers.AddOrUpdate(c => c.Email, c82);
			db.SaveChanges();

			Customer c83 = new Customer();
			c83.FirstName = "Jonathan";
			c83.LastName = "Fowler";
			c83.Gender = "Male";
			c83.Email = "jfowler2a@cargocollective.com";
			c83.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Weekly");
			c83.ReferredFrom = "amazon.de";
			c83.AverageSale = 544.85m;
			db.Customers.AddOrUpdate(c => c.Email, c83);
			db.SaveChanges();

			Customer c84 = new Customer();
			c84.FirstName = "Henry";
			c84.LastName = "Black";
			c84.Gender = "Male";
			c84.Email = "hblack2b@lulu.com";
			c84.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Yearly");
			c84.ReferredFrom = "ft.com";
			c84.AverageSale = 387.98m;
			db.Customers.AddOrUpdate(c => c.Email, c84);
			db.SaveChanges();

			Customer c85 = new Customer();
			c85.FirstName = "Evelyn";
			c85.LastName = "Garcia";
			c85.Gender = "Female";
			c85.Email = "egarcia2c@studiopress.com";
			c85.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Yearly");
			c85.ReferredFrom = "instagram.com";
			c85.AverageSale = 323m;
			db.Customers.AddOrUpdate(c => c.Email, c85);
			db.SaveChanges();

			Customer c86 = new Customer();
			c86.FirstName = "Brandon";
			c86.LastName = "West";
			c86.Gender = "Male";
			c86.Email = "bwest2d@storify.com";
			c86.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Seldom");
			c86.ReferredFrom = "redcross.org";
			c86.AverageSale = 581.74m;
			db.Customers.AddOrUpdate(c => c.Email, c86);
			db.SaveChanges();

			Customer c87 = new Customer();
			c87.FirstName = "Lois";
			c87.LastName = "Ortiz";
			c87.Gender = "Female";
			c87.Email = "lortiz2e@ocn.ne.jp";
			c87.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Yearly");
			c87.ReferredFrom = "bloglovin.com";
			c87.AverageSale = 530.48m;
			db.Customers.AddOrUpdate(c => c.Email, c87);
			db.SaveChanges();

			Customer c88 = new Customer();
			c88.FirstName = "Philip";
			c88.LastName = "Clark";
			c88.Gender = "Male";
			c88.Email = "pclark2f@sogou.com";
			c88.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Yearly");
			c88.ReferredFrom = "washingtonpost.com";
			c88.AverageSale = 464.9m;
			db.Customers.AddOrUpdate(c => c.Email, c88);
			db.SaveChanges();

			Customer c89 = new Customer();
			c89.FirstName = "Shawn";
			c89.LastName = "Chapman";
			c89.Gender = "Male";
			c89.Email = "schapman2g@dot.gov";
			c89.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Weekly");
			c89.ReferredFrom = "mayoclinic.com";
			c89.AverageSale = 625.26m;
			db.Customers.AddOrUpdate(c => c.Email, c89);
			db.SaveChanges();

			Customer c90 = new Customer();
			c90.FirstName = "Lisa";
			c90.LastName = "Alvarez";
			c90.Gender = "Female";
			c90.Email = "lalvarez2h@amazon.co.jp";
			c90.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Monthly");
			c90.ReferredFrom = "illinois.edu";
			c90.AverageSale = 350.96m;
			db.Customers.AddOrUpdate(c => c.Email, c90);
			db.SaveChanges();

			Customer c91 = new Customer();
			c91.FirstName = "Fred";
			c91.LastName = "Marshall";
			c91.Gender = "Male";
			c91.Email = "fmarshall2i@gizmodo.com";
			c91.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Never");
			c91.ReferredFrom = "nasa.gov";
			c91.AverageSale = 443.48m;
			db.Customers.AddOrUpdate(c => c.Email, c91);
			db.SaveChanges();

			Customer c92 = new Customer();
			c92.FirstName = "Lori";
			c92.LastName = "Fields";
			c92.Gender = "Female";
			c92.Email = "lfields2j@cnn.com";
			c92.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Once");
			c92.ReferredFrom = "shop-pro.jp";
			c92.AverageSale = 314.85m;
			db.Customers.AddOrUpdate(c => c.Email, c92);
			db.SaveChanges();

			Customer c93 = new Customer();
			c93.FirstName = "Aaron";
			c93.LastName = "Martin";
			c93.Gender = "Male";
			c93.Email = "amartin2k@dyndns.org";
			c93.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Never");
			c93.ReferredFrom = "ft.com";
			c93.AverageSale = 426.42m;
			db.Customers.AddOrUpdate(c => c.Email, c93);
			db.SaveChanges();

			Customer c94 = new Customer();
			c94.FirstName = "Diane";
			c94.LastName = "Franklin";
			c94.Gender = "Female";
			c94.Email = "dfranklin2l@discuz.net";
			c94.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Daily");
			c94.ReferredFrom = "istockphoto.com";
			c94.AverageSale = 496.25m;
			db.Customers.AddOrUpdate(c => c.Email, c94);
			db.SaveChanges();

			Customer c95 = new Customer();
			c95.FirstName = "Anne";
			c95.LastName = "George";
			c95.Gender = "Female";
			c95.Email = "ageorge2m@icio.us";
			c95.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Often");
			c95.ReferredFrom = "state.tx.us";
			c95.AverageSale = 472.28m;
			db.Customers.AddOrUpdate(c => c.Email, c95);
			db.SaveChanges();

			Customer c96 = new Customer();
			c96.FirstName = "Julia";
			c96.LastName = "Fields";
			c96.Gender = "Female";
			c96.Email = "jfields2n@army.mil";
			c96.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Daily");
			c96.ReferredFrom = "narod.ru";
			c96.AverageSale = 463.62m;
			db.Customers.AddOrUpdate(c => c.Email, c96);
			db.SaveChanges();

			Customer c97 = new Customer();
			c97.FirstName = "Billy";
			c97.LastName = "Stone";
			c97.Gender = "Male";
			c97.Email = "bstone2o@slideshare.net";
			c97.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Monthly");
			c97.ReferredFrom = "unicef.org";
			c97.AverageSale = 413.91m;
			db.Customers.AddOrUpdate(c => c.Email, c97);
			db.SaveChanges();

			Customer c98 = new Customer();
			c98.FirstName = "Ruth";
			c98.LastName = "Fields";
			c98.Gender = "Female";
			c98.Email = "rfields2p@bloglovin.com";
			c98.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Often");
			c98.ReferredFrom = "about.me";
			c98.AverageSale = 522.3m;
			db.Customers.AddOrUpdate(c => c.Email, c98);
			db.SaveChanges();

			Customer c99 = new Customer();
			c99.FirstName = "Sandra";
			c99.LastName = "Walker";
			c99.Gender = "Female";
			c99.Email = "swalker2q@stumbleupon.com";
			c99.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Often");
			c99.ReferredFrom = "telegraph.co.uk";
			c99.AverageSale = 336.13m;
			db.Customers.AddOrUpdate(c => c.Email, c99);
			db.SaveChanges();

			Customer c100 = new Customer();
			c100.FirstName = "Billy";
			c100.LastName = "Rice";
			c100.Gender = "Male";
			c100.Email = "brice2r@va.gov";
			c100.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Once");
			c100.ReferredFrom = "phoca.cz";
			c100.AverageSale = 352.04m;
			db.Customers.AddOrUpdate(c => c.Email, c100);
			db.SaveChanges();

			Customer c101 = new Customer();
			c101.FirstName = "Rose";
			c101.LastName = "Wright";
			c101.Gender = "Female";
			c101.Email = "rwright2s@google.ca";
			c101.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Never");
			c101.ReferredFrom = "wunderground.com";
			c101.AverageSale = 420.17m;
			db.Customers.AddOrUpdate(c => c.Email, c101);
			db.SaveChanges();

			Customer c102 = new Customer();
			c102.FirstName = "Arthur";
			c102.LastName = "Ward";
			c102.Gender = "Male";
			c102.Email = "award2t@github.com";
			c102.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Weekly");
			c102.ReferredFrom = "slideshare.net";
			c102.AverageSale = 443.92m;
			db.Customers.AddOrUpdate(c => c.Email, c102);
			db.SaveChanges();

			Customer c103 = new Customer();
			c103.FirstName = "Phillip";
			c103.LastName = "Castillo";
			c103.Gender = "Male";
			c103.Email = "pcastillo2u@techcrunch.com";
			c103.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Never");
			c103.ReferredFrom = "whitehouse.gov";
			c103.AverageSale = 332.88m;
			db.Customers.AddOrUpdate(c => c.Email, c103);
			db.SaveChanges();

			Customer c104 = new Customer();
			c104.FirstName = "Mary";
			c104.LastName = "Boyd";
			c104.Gender = "Female";
			c104.Email = "mboyd2v@reddit.com";
			c104.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Daily");
			c104.ReferredFrom = "mit.edu";
			c104.AverageSale = 373.42m;
			db.Customers.AddOrUpdate(c => c.Email, c104);
			db.SaveChanges();

			Customer c105 = new Customer();
			c105.FirstName = "Bobby";
			c105.LastName = "Gonzalez";
			c105.Gender = "Male";
			c105.Email = "bgonzalez2w@who.int";
			c105.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Never");
			c105.ReferredFrom = "illinois.edu";
			c105.AverageSale = 390.69m;
			db.Customers.AddOrUpdate(c => c.Email, c105);
			db.SaveChanges();

			Customer c106 = new Customer();
			c106.FirstName = "Gregory";
			c106.LastName = "James";
			c106.Gender = "Male";
			c106.Email = "gjames2x@instagram.com";
			c106.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Yearly");
			c106.ReferredFrom = "cornell.edu";
			c106.AverageSale = 374.35m;
			db.Customers.AddOrUpdate(c => c.Email, c106);
			db.SaveChanges();

			Customer c107 = new Customer();
			c107.FirstName = "Betty";
			c107.LastName = "Daniels";
			c107.Gender = "Female";
			c107.Email = "bdaniels2y@so-net.ne.jp";
			c107.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Often");
			c107.ReferredFrom = "g.co";
			c107.AverageSale = 487.53m;
			db.Customers.AddOrUpdate(c => c.Email, c107);
			db.SaveChanges();

			Customer c108 = new Customer();
			c108.FirstName = "Michelle";
			c108.LastName = "Marshall";
			c108.Gender = "Female";
			c108.Email = "mmarshall2z@princeton.edu";
			c108.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Yearly");
			c108.ReferredFrom = "indiegogo.com";
			c108.AverageSale = 471.91m;
			db.Customers.AddOrUpdate(c => c.Email, c108);
			db.SaveChanges();

			Customer c109 = new Customer();
			c109.FirstName = "Elizabeth";
			c109.LastName = "Jones";
			c109.Gender = "Female";
			c109.Email = "ejones30@nifty.com";
			c109.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Seldom");
			c109.ReferredFrom = "indiegogo.com";
			c109.AverageSale = 480.98m;
			db.Customers.AddOrUpdate(c => c.Email, c109);
			db.SaveChanges();

			Customer c110 = new Customer();
			c110.FirstName = "George";
			c110.LastName = "Webb";
			c110.Gender = "Male";
			c110.Email = "gwebb31@ebay.com";
			c110.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Often");
			c110.ReferredFrom = "answers.com";
			c110.AverageSale = 257.12m;
			db.Customers.AddOrUpdate(c => c.Email, c110);
			db.SaveChanges();

			Customer c111 = new Customer();
			c111.FirstName = "Judy";
			c111.LastName = "Burke";
			c111.Gender = "Female";
			c111.Email = "jburke32@slashdot.org";
			c111.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Seldom");
			c111.ReferredFrom = "unblog.fr";
			c111.AverageSale = 532.37m;
			db.Customers.AddOrUpdate(c => c.Email, c111);
			db.SaveChanges();

			Customer c112 = new Customer();
			c112.FirstName = "Denise";
			c112.LastName = "Hill";
			c112.Gender = "Female";
			c112.Email = "dhill33@a8.net";
			c112.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Never");
			c112.ReferredFrom = "gravatar.com";
			c112.AverageSale = 409.76m;
			db.Customers.AddOrUpdate(c => c.Email, c112);
			db.SaveChanges();

			Customer c113 = new Customer();
			c113.FirstName = "Wanda";
			c113.LastName = "Alvarez";
			c113.Gender = "Female";
			c113.Email = "walvarez34@java.com";
			c113.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Often");
			c113.ReferredFrom = "google.ca";
			c113.AverageSale = 225.02m;
			db.Customers.AddOrUpdate(c => c.Email, c113);
			db.SaveChanges();

			Customer c114 = new Customer();
			c114.FirstName = "Lois";
			c114.LastName = "Simpson";
			c114.Gender = "Female";
			c114.Email = "lsimpson35@istockphoto.com";
			c114.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Once");
			c114.ReferredFrom = "google.it";
			c114.AverageSale = 376.82m;
			db.Customers.AddOrUpdate(c => c.Email, c114);
			db.SaveChanges();

			Customer c115 = new Customer();
			c115.FirstName = "Johnny";
			c115.LastName = "Garcia";
			c115.Gender = "Male";
			c115.Email = "jgarcia36@nba.com";
			c115.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Once");
			c115.ReferredFrom = "last.fm";
			c115.AverageSale = 461.89m;
			db.Customers.AddOrUpdate(c => c.Email, c115);
			db.SaveChanges();

			Customer c116 = new Customer();
			c116.FirstName = "Lisa";
			c116.LastName = "Lane";
			c116.Gender = "Female";
			c116.Email = "llane37@github.com";
			c116.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Yearly");
			c116.ReferredFrom = "people.com.cn";
			c116.AverageSale = 223.83m;
			db.Customers.AddOrUpdate(c => c.Email, c116);
			db.SaveChanges();

			Customer c117 = new Customer();
			c117.FirstName = "Sean";
			c117.LastName = "Richardson";
			c117.Gender = "Male";
			c117.Email = "srichardson38@ycombinator.com";
			c117.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Once");
			c117.ReferredFrom = "indiatimes.com";
			c117.AverageSale = 406.25m;
			db.Customers.AddOrUpdate(c => c.Email, c117);
			db.SaveChanges();

			Customer c118 = new Customer();
			c118.FirstName = "Kimberly";
			c118.LastName = "Oliver";
			c118.Gender = "Female";
			c118.Email = "koliver39@aol.com";
			c118.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Seldom");
			c118.ReferredFrom = "shutterfly.com";
			c118.AverageSale = 494.49m;
			db.Customers.AddOrUpdate(c => c.Email, c118);
			db.SaveChanges();

			Customer c119 = new Customer();
			c119.FirstName = "Robin";
			c119.LastName = "Woods";
			c119.Gender = "Female";
			c119.Email = "rwoods3a@dedecms.com";
			c119.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Yearly");
			c119.ReferredFrom = "devhub.com";
			c119.AverageSale = 510.72m;
			db.Customers.AddOrUpdate(c => c.Email, c119);
			db.SaveChanges();

			Customer c120 = new Customer();
			c120.FirstName = "Todd";
			c120.LastName = "Ryan";
			c120.Gender = "Male";
			c120.Email = "tryan3b@printfriendly.com";
			c120.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Monthly");
			c120.ReferredFrom = "gravatar.com";
			c120.AverageSale = 551.37m;
			db.Customers.AddOrUpdate(c => c.Email, c120);
			db.SaveChanges();

			Customer c121 = new Customer();
			c121.FirstName = "Kimberly";
			c121.LastName = "Thomas";
			c121.Gender = "Female";
			c121.Email = "kthomas3c@wisc.edu";
			c121.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Often");
			c121.ReferredFrom = "si.edu";
			c121.AverageSale = 506.98m;
			db.Customers.AddOrUpdate(c => c.Email, c121);
			db.SaveChanges();

			Customer c122 = new Customer();
			c122.FirstName = "Theresa";
			c122.LastName = "Bennett";
			c122.Gender = "Female";
			c122.Email = "tbennett3d@ezinearticles.com";
			c122.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Often");
			c122.ReferredFrom = "typepad.com";
			c122.AverageSale = 512.94m;
			db.Customers.AddOrUpdate(c => c.Email, c122);
			db.SaveChanges();

			Customer c123 = new Customer();
			c123.FirstName = "Raymond";
			c123.LastName = "Bishop";
			c123.Gender = "Male";
			c123.Email = "rbishop3e@i2i.jp";
			c123.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Daily");
			c123.ReferredFrom = "phpbb.com";
			c123.AverageSale = 651.02m;
			db.Customers.AddOrUpdate(c => c.Email, c123);
			db.SaveChanges();

			Customer c124 = new Customer();
			c124.FirstName = "Elizabeth";
			c124.LastName = "Adams";
			c124.Gender = "Female";
			c124.Email = "eadams3f@parallels.com";
			c124.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Seldom");
			c124.ReferredFrom = "xing.com";
			c124.AverageSale = 215.65m;
			db.Customers.AddOrUpdate(c => c.Email, c124);
			db.SaveChanges();

			Customer c125 = new Customer();
			c125.FirstName = "Tina";
			c125.LastName = "Daniels";
			c125.Gender = "Female";
			c125.Email = "tdaniels3g@artisteer.com";
			c125.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Often");
			c125.ReferredFrom = "myspace.com";
			c125.AverageSale = 387.38m;
			db.Customers.AddOrUpdate(c => c.Email, c125);
			db.SaveChanges();

			Customer c126 = new Customer();
			c126.FirstName = "Susan";
			c126.LastName = "Bishop";
			c126.Gender = "Female";
			c126.Email = "sbishop3h@hud.gov";
			c126.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Once");
			c126.ReferredFrom = "mashable.com";
			c126.AverageSale = 350.87m;
			db.Customers.AddOrUpdate(c => c.Email, c126);
			db.SaveChanges();

			Customer c127 = new Customer();
			c127.FirstName = "Albert";
			c127.LastName = "Romero";
			c127.Gender = "Male";
			c127.Email = "aromero3i@google.fr";
			c127.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Weekly");
			c127.ReferredFrom = "dion.ne.jp";
			c127.AverageSale = 383.48m;
			db.Customers.AddOrUpdate(c => c.Email, c127);
			db.SaveChanges();

			Customer c128 = new Customer();
			c128.FirstName = "Ruby";
			c128.LastName = "Gordon";
			c128.Gender = "Female";
			c128.Email = "rgordon3j@ameblo.jp";
			c128.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Seldom");
			c128.ReferredFrom = "wikispaces.com";
			c128.AverageSale = 263.97m;
			db.Customers.AddOrUpdate(c => c.Email, c128);
			db.SaveChanges();

			Customer c129 = new Customer();
			c129.FirstName = "Kathryn";
			c129.LastName = "Foster";
			c129.Gender = "Female";
			c129.Email = "kfoster3k@discuz.net";
			c129.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Never");
			c129.ReferredFrom = "rambler.ru";
			c129.AverageSale = 209.72m;
			db.Customers.AddOrUpdate(c => c.Email, c129);
			db.SaveChanges();

			Customer c130 = new Customer();
			c130.FirstName = "Joseph";
			c130.LastName = "Thompson";
			c130.Gender = "Male";
			c130.Email = "jthompson3l@yellowpages.com";
			c130.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Weekly");
			c130.ReferredFrom = "nhs.uk";
			c130.AverageSale = 202.12m;
			db.Customers.AddOrUpdate(c => c.Email, c130);
			db.SaveChanges();

			Customer c131 = new Customer();
			c131.FirstName = "Joan";
			c131.LastName = "Rogers";
			c131.Gender = "Female";
			c131.Email = "jrogers3m@disqus.com";
			c131.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Yearly");
			c131.ReferredFrom = "ox.ac.uk";
			c131.AverageSale = 370.83m;
			db.Customers.AddOrUpdate(c => c.Email, c131);
			db.SaveChanges();

			Customer c132 = new Customer();
			c132.FirstName = "Ernest";
			c132.LastName = "Williamson";
			c132.Gender = "Male";
			c132.Email = "ewilliamson3n@g.co";
			c132.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Often");
			c132.ReferredFrom = "livejournal.com";
			c132.AverageSale = 394.32m;
			db.Customers.AddOrUpdate(c => c.Email, c132);
			db.SaveChanges();

			Customer c133 = new Customer();
			c133.FirstName = "Julie";
			c133.LastName = "Simpson";
			c133.Gender = "Female";
			c133.Email = "jsimpson3o@cdc.gov";
			c133.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Daily");
			c133.ReferredFrom = "4shared.com";
			c133.AverageSale = 377.78m;
			db.Customers.AddOrUpdate(c => c.Email, c133);
			db.SaveChanges();

			Customer c134 = new Customer();
			c134.FirstName = "Joshua";
			c134.LastName = "Simpson";
			c134.Gender = "Male";
			c134.Email = "jsimpson3p@feedburner.com";
			c134.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Often");
			c134.ReferredFrom = "networksolutions.com";
			c134.AverageSale = 501.88m;
			db.Customers.AddOrUpdate(c => c.Email, c134);
			db.SaveChanges();

			Customer c135 = new Customer();
			c135.FirstName = "Anna";
			c135.LastName = "Nelson";
			c135.Gender = "Female";
			c135.Email = "anelson3q@reference.com";
			c135.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Weekly");
			c135.ReferredFrom = "elegantthemes.com";
			c135.AverageSale = 217.7m;
			db.Customers.AddOrUpdate(c => c.Email, c135);
			db.SaveChanges();

			Customer c136 = new Customer();
			c136.FirstName = "Stephen";
			c136.LastName = "Bradley";
			c136.Gender = "Male";
			c136.Email = "sbradley3r@opensource.org";
			c136.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Never");
			c136.ReferredFrom = "desdev.cn";
			c136.AverageSale = 402.05m;
			db.Customers.AddOrUpdate(c => c.Email, c136);
			db.SaveChanges();

			Customer c137 = new Customer();
			c137.FirstName = "Frank";
			c137.LastName = "Torres";
			c137.Gender = "Male";
			c137.Email = "ftorres3s@cpanel.net";
			c137.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Daily");
			c137.ReferredFrom = "delicious.com";
			c137.AverageSale = 488.95m;
			db.Customers.AddOrUpdate(c => c.Email, c137);
			db.SaveChanges();

			Customer c138 = new Customer();
			c138.FirstName = "Ashley";
			c138.LastName = "Martinez";
			c138.Gender = "Female";
			c138.Email = "amartinez3t@forbes.com";
			c138.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Daily");
			c138.ReferredFrom = "dion.ne.jp";
			c138.AverageSale = 317.17m;
			db.Customers.AddOrUpdate(c => c.Email, c138);
			db.SaveChanges();

			Customer c139 = new Customer();
			c139.FirstName = "Fred";
			c139.LastName = "Stevens";
			c139.Gender = "Male";
			c139.Email = "fstevens3u@vinaora.com";
			c139.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Daily");
			c139.ReferredFrom = "thetimes.co.uk";
			c139.AverageSale = 380.61m;
			db.Customers.AddOrUpdate(c => c.Email, c139);
			db.SaveChanges();

			Customer c140 = new Customer();
			c140.FirstName = "Gloria";
			c140.LastName = "Jordan";
			c140.Gender = "Female";
			c140.Email = "gjordan3v@nbcnews.com";
			c140.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Daily");
			c140.ReferredFrom = "foxnews.com";
			c140.AverageSale = 386.8m;
			db.Customers.AddOrUpdate(c => c.Email, c140);
			db.SaveChanges();

			Customer c141 = new Customer();
			c141.FirstName = "Cheryl";
			c141.LastName = "Scott";
			c141.Gender = "Female";
			c141.Email = "cscott3w@yale.edu";
			c141.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Never");
			c141.ReferredFrom = "bigcartel.com";
			c141.AverageSale = 676.43m;
			db.Customers.AddOrUpdate(c => c.Email, c141);
			db.SaveChanges();

			Customer c142 = new Customer();
			c142.FirstName = "Margaret";
			c142.LastName = "Palmer";
			c142.Gender = "Female";
			c142.Email = "mpalmer3x@unc.edu";
			c142.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Yearly");
			c142.ReferredFrom = "nydailynews.com";
			c142.AverageSale = 461.47m;
			db.Customers.AddOrUpdate(c => c.Email, c142);
			db.SaveChanges();

			Customer c143 = new Customer();
			c143.FirstName = "Patricia";
			c143.LastName = "Long";
			c143.Gender = "Female";
			c143.Email = "plong3y@surveymonkey.com";
			c143.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Yearly");
			c143.ReferredFrom = "joomla.org";
			c143.AverageSale = 275.17m;
			db.Customers.AddOrUpdate(c => c.Email, c143);
			db.SaveChanges();

			Customer c144 = new Customer();
			c144.FirstName = "Anne";
			c144.LastName = "Evans";
			c144.Gender = "Female";
			c144.Email = "aevans3z@istockphoto.com";
			c144.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Yearly");
			c144.ReferredFrom = "digg.com";
			c144.AverageSale = 434.11m;
			db.Customers.AddOrUpdate(c => c.Email, c144);
			db.SaveChanges();

			Customer c145 = new Customer();
			c145.FirstName = "Judith";
			c145.LastName = "Morrison";
			c145.Gender = "Female";
			c145.Email = "jmorrison40@furl.net";
			c145.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Often");
			c145.ReferredFrom = "unc.edu";
			c145.AverageSale = 354.06m;
			db.Customers.AddOrUpdate(c => c.Email, c145);
			db.SaveChanges();

			Customer c146 = new Customer();
			c146.FirstName = "Bobby";
			c146.LastName = "Simpson";
			c146.Gender = "Male";
			c146.Email = "bsimpson41@github.com";
			c146.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Seldom");
			c146.ReferredFrom = "marriott.com";
			c146.AverageSale = 447.52m;
			db.Customers.AddOrUpdate(c => c.Email, c146);
			db.SaveChanges();

			Customer c147 = new Customer();
			c147.FirstName = "Katherine";
			c147.LastName = "Pierce";
			c147.Gender = "Female";
			c147.Email = "kpierce42@trellian.com";
			c147.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Yearly");
			c147.ReferredFrom = "uiuc.edu";
			c147.AverageSale = 442.21m;
			db.Customers.AddOrUpdate(c => c.Email, c147);
			db.SaveChanges();

			Customer c148 = new Customer();
			c148.FirstName = "Adam";
			c148.LastName = "Gibson";
			c148.Gender = "Male";
			c148.Email = "agibson43@whitehouse.gov";
			c148.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Seldom");
			c148.ReferredFrom = "latimes.com";
			c148.AverageSale = 482.29m;
			db.Customers.AddOrUpdate(c => c.Email, c148);
			db.SaveChanges();

			Customer c149 = new Customer();
			c149.FirstName = "Anna";
			c149.LastName = "Grant";
			c149.Gender = "Female";
			c149.Email = "agrant44@amazon.co.jp";
			c149.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Never");
			c149.ReferredFrom = "netlog.com";
			c149.AverageSale = 298.85m;
			db.Customers.AddOrUpdate(c => c.Email, c149);
			db.SaveChanges();

			Customer c150 = new Customer();
			c150.FirstName = "Jose";
			c150.LastName = "Perkins";
			c150.Gender = "Male";
			c150.Email = "jperkins45@psu.edu";
			c150.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Seldom");
			c150.ReferredFrom = "myspace.com";
			c150.AverageSale = 263.18m;
			db.Customers.AddOrUpdate(c => c.Email, c150);
			db.SaveChanges();

			Customer c151 = new Customer();
			c151.FirstName = "Anna";
			c151.LastName = "Edwards";
			c151.Gender = "Female";
			c151.Email = "aedwards46@weibo.com";
			c151.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Seldom");
			c151.ReferredFrom = "elegantthemes.com";
			c151.AverageSale = 383.73m;
			db.Customers.AddOrUpdate(c => c.Email, c151);
			db.SaveChanges();

			Customer c152 = new Customer();
			c152.FirstName = "Edward";
			c152.LastName = "Richards";
			c152.Gender = "Male";
			c152.Email = "erichards47@nba.com";
			c152.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Daily");
			c152.ReferredFrom = "technorati.com";
			c152.AverageSale = 378.91m;
			db.Customers.AddOrUpdate(c => c.Email, c152);
			db.SaveChanges();

			Customer c153 = new Customer();
			c153.FirstName = "Lois";
			c153.LastName = "Anderson";
			c153.Gender = "Female";
			c153.Email = "landerson48@ovh.net";
			c153.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Weekly");
			c153.ReferredFrom = "columbia.edu";
			c153.AverageSale = 341.94m;
			db.Customers.AddOrUpdate(c => c.Email, c153);
			db.SaveChanges();

			Customer c154 = new Customer();
			c154.FirstName = "Julia";
			c154.LastName = "Chavez";
			c154.Gender = "Female";
			c154.Email = "jchavez49@mozilla.com";
			c154.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Seldom");
			c154.ReferredFrom = "mac.com";
			c154.AverageSale = 132.88m;
			db.Customers.AddOrUpdate(c => c.Email, c154);
			db.SaveChanges();

			Customer c155 = new Customer();
			c155.FirstName = "Ronald";
			c155.LastName = "Banks";
			c155.Gender = "Male";
			c155.Email = "rbanks4a@edublogs.org";
			c155.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Weekly");
			c155.ReferredFrom = "sun.com";
			c155.AverageSale = 225.88m;
			db.Customers.AddOrUpdate(c => c.Email, c155);
			db.SaveChanges();

			Customer c156 = new Customer();
			c156.FirstName = "Carlos";
			c156.LastName = "Rose";
			c156.Gender = "Male";
			c156.Email = "crose4b@bbb.org";
			c156.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Often");
			c156.ReferredFrom = "feedburner.com";
			c156.AverageSale = 488.33m;
			db.Customers.AddOrUpdate(c => c.Email, c156);
			db.SaveChanges();

			Customer c157 = new Customer();
			c157.FirstName = "Elizabeth";
			c157.LastName = "Hanson";
			c157.Gender = "Female";
			c157.Email = "ehanson4c@dedecms.com";
			c157.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Daily");
			c157.ReferredFrom = "lulu.com";
			c157.AverageSale = 487.87m;
			db.Customers.AddOrUpdate(c => c.Email, c157);
			db.SaveChanges();

			Customer c158 = new Customer();
			c158.FirstName = "Chris";
			c158.LastName = "Brown";
			c158.Gender = "Male";
			c158.Email = "cbrown4d@technorati.com";
			c158.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Seldom");
			c158.ReferredFrom = "printfriendly.com";
			c158.AverageSale = 287.91m;
			db.Customers.AddOrUpdate(c => c.Email, c158);
			db.SaveChanges();

			Customer c159 = new Customer();
			c159.FirstName = "Anne";
			c159.LastName = "Woods";
			c159.Gender = "Female";
			c159.Email = "awoods4e@elpais.com";
			c159.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Monthly");
			c159.ReferredFrom = "stumbleupon.com";
			c159.AverageSale = 333.79m;
			db.Customers.AddOrUpdate(c => c.Email, c159);
			db.SaveChanges();

			Customer c160 = new Customer();
			c160.FirstName = "Julia";
			c160.LastName = "Marshall";
			c160.Gender = "Female";
			c160.Email = "jmarshall4f@behance.net";
			c160.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Seldom");
			c160.ReferredFrom = "howstuffworks.com";
			c160.AverageSale = 239.04m;
			db.Customers.AddOrUpdate(c => c.Email, c160);
			db.SaveChanges();

			Customer c161 = new Customer();
			c161.FirstName = "Willie";
			c161.LastName = "Bowman";
			c161.Gender = "Male";
			c161.Email = "wbowman4g@freewebs.com";
			c161.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Once");
			c161.ReferredFrom = "hexun.com";
			c161.AverageSale = 461.56m;
			db.Customers.AddOrUpdate(c => c.Email, c161);
			db.SaveChanges();

			Customer c162 = new Customer();
			c162.FirstName = "Todd";
			c162.LastName = "Phillips";
			c162.Gender = "Male";
			c162.Email = "tphillips4h@seattletimes.com";
			c162.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Weekly");
			c162.ReferredFrom = "economist.com";
			c162.AverageSale = 459.84m;
			db.Customers.AddOrUpdate(c => c.Email, c162);
			db.SaveChanges();

			Customer c163 = new Customer();
			c163.FirstName = "Scott";
			c163.LastName = "Coleman";
			c163.Gender = "Male";
			c163.Email = "scoleman4i@upenn.edu";
			c163.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Daily");
			c163.ReferredFrom = "biglobe.ne.jp";
			c163.AverageSale = 446.79m;
			db.Customers.AddOrUpdate(c => c.Email, c163);
			db.SaveChanges();

			Customer c164 = new Customer();
			c164.FirstName = "Samuel";
			c164.LastName = "Kim";
			c164.Gender = "Male";
			c164.Email = "skim4j@chicagotribune.com";
			c164.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Daily");
			c164.ReferredFrom = "unblog.fr";
			c164.AverageSale = 419.59m;
			db.Customers.AddOrUpdate(c => c.Email, c164);
			db.SaveChanges();

			Customer c165 = new Customer();
			c165.FirstName = "Diane";
			c165.LastName = "Harvey";
			c165.Gender = "Female";
			c165.Email = "dharvey4k@scientificamerican.com";
			c165.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Monthly");
			c165.ReferredFrom = "si.edu";
			c165.AverageSale = 465.96m;
			db.Customers.AddOrUpdate(c => c.Email, c165);
			db.SaveChanges();

			Customer c166 = new Customer();
			c166.FirstName = "Martha";
			c166.LastName = "Butler";
			c166.Gender = "Female";
			c166.Email = "mbutler4l@naver.com";
			c166.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Yearly");
			c166.ReferredFrom = "people.com.cn";
			c166.AverageSale = 449.26m;
			db.Customers.AddOrUpdate(c => c.Email, c166);
			db.SaveChanges();

			Customer c167 = new Customer();
			c167.FirstName = "Michelle";
			c167.LastName = "Gutierrez";
			c167.Gender = "Female";
			c167.Email = "mgutierrez4m@apache.org";
			c167.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Seldom");
			c167.ReferredFrom = "usnews.com";
			c167.AverageSale = 468.96m;
			db.Customers.AddOrUpdate(c => c.Email, c167);
			db.SaveChanges();

			Customer c168 = new Customer();
			c168.FirstName = "Earl";
			c168.LastName = "Gutierrez";
			c168.Gender = "Male";
			c168.Email = "egutierrez4n@oakley.com";
			c168.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Daily");
			c168.ReferredFrom = "umich.edu";
			c168.AverageSale = 343.47m;
			db.Customers.AddOrUpdate(c => c.Email, c168);
			db.SaveChanges();

			Customer c169 = new Customer();
			c169.FirstName = "Betty";
			c169.LastName = "Vasquez";
			c169.Gender = "Female";
			c169.Email = "bvasquez4o@google.com.br";
			c169.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Weekly");
			c169.ReferredFrom = "tripadvisor.com";
			c169.AverageSale = 299.1m;
			db.Customers.AddOrUpdate(c => c.Email, c169);
			db.SaveChanges();

			Customer c170 = new Customer();
			c170.FirstName = "Kelly";
			c170.LastName = "Hawkins";
			c170.Gender = "Female";
			c170.Email = "khawkins4p@friendfeed.com";
			c170.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Daily");
			c170.ReferredFrom = "latimes.com";
			c170.AverageSale = 461.83m;
			db.Customers.AddOrUpdate(c => c.Email, c170);
			db.SaveChanges();

			Customer c171 = new Customer();
			c171.FirstName = "Ann";
			c171.LastName = "Phillips";
			c171.Gender = "Female";
			c171.Email = "aphillips4q@netscape.com";
			c171.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Yearly");
			c171.ReferredFrom = "ning.com";
			c171.AverageSale = 492.07m;
			db.Customers.AddOrUpdate(c => c.Email, c171);
			db.SaveChanges();

			Customer c172 = new Customer();
			c172.FirstName = "Karen";
			c172.LastName = "Thompson";
			c172.Gender = "Female";
			c172.Email = "kthompson4r@cdbaby.com";
			c172.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Often");
			c172.ReferredFrom = "engadget.com";
			c172.AverageSale = 521.75m;
			db.Customers.AddOrUpdate(c => c.Email, c172);
			db.SaveChanges();

			Customer c173 = new Customer();
			c173.FirstName = "Teresa";
			c173.LastName = "Reynolds";
			c173.Gender = "Female";
			c173.Email = "treynolds4s@e-recht24.de";
			c173.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Once");
			c173.ReferredFrom = "boston.com";
			c173.AverageSale = 376.09m;
			db.Customers.AddOrUpdate(c => c.Email, c173);
			db.SaveChanges();

			Customer c174 = new Customer();
			c174.FirstName = "Martin";
			c174.LastName = "Ramos";
			c174.Gender = "Male";
			c174.Email = "mramos4t@nps.gov";
			c174.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Weekly");
			c174.ReferredFrom = "cbsnews.com";
			c174.AverageSale = 371.08m;
			db.Customers.AddOrUpdate(c => c.Email, c174);
			db.SaveChanges();

			Customer c175 = new Customer();
			c175.FirstName = "Nicole";
			c175.LastName = "Hill";
			c175.Gender = "Female";
			c175.Email = "nhill4u@dagondesign.com";
			c175.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Daily");
			c175.ReferredFrom = "ibm.com";
			c175.AverageSale = 257.84m;
			db.Customers.AddOrUpdate(c => c.Email, c175);
			db.SaveChanges();

			Customer c176 = new Customer();
			c176.FirstName = "Sandra";
			c176.LastName = "Payne";
			c176.Gender = "Female";
			c176.Email = "spayne4v@yellowpages.com";
			c176.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Seldom");
			c176.ReferredFrom = "ibm.com";
			c176.AverageSale = 444.25m;
			db.Customers.AddOrUpdate(c => c.Email, c176);
			db.SaveChanges();

			Customer c177 = new Customer();
			c177.FirstName = "Christopher";
			c177.LastName = "Williamson";
			c177.Gender = "Male";
			c177.Email = "cwilliamson4w@wufoo.com";
			c177.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Once");
			c177.ReferredFrom = "smh.com.au";
			c177.AverageSale = 308.11m;
			db.Customers.AddOrUpdate(c => c.Email, c177);
			db.SaveChanges();

			Customer c178 = new Customer();
			c178.FirstName = "Teresa";
			c178.LastName = "Garcia";
			c178.Gender = "Female";
			c178.Email = "tgarcia4x@springer.com";
			c178.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Seldom");
			c178.ReferredFrom = "sitemeter.com";
			c178.AverageSale = 565.2m;
			db.Customers.AddOrUpdate(c => c.Email, c178);
			db.SaveChanges();

			Customer c179 = new Customer();
			c179.FirstName = "Craig";
			c179.LastName = "Snyder";
			c179.Gender = "Male";
			c179.Email = "csnyder4y@sphinn.com";
			c179.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Once");
			c179.ReferredFrom = "devhub.com";
			c179.AverageSale = 403.86m;
			db.Customers.AddOrUpdate(c => c.Email, c179);
			db.SaveChanges();

			Customer c180 = new Customer();
			c180.FirstName = "Billy";
			c180.LastName = "Kennedy";
			c180.Gender = "Male";
			c180.Email = "bkennedy4z@posterous.com";
			c180.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Often");
			c180.ReferredFrom = "over-blog.com";
			c180.AverageSale = 465.62m;
			db.Customers.AddOrUpdate(c => c.Email, c180);
			db.SaveChanges();

			Customer c181 = new Customer();
			c181.FirstName = "Debra";
			c181.LastName = "Mcdonald";
			c181.Gender = "Female";
			c181.Email = "dmcdonald50@uol.com.br";
			c181.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Weekly");
			c181.ReferredFrom = "netvibes.com";
			c181.AverageSale = 159.68m;
			db.Customers.AddOrUpdate(c => c.Email, c181);
			db.SaveChanges();

			Customer c182 = new Customer();
			c182.FirstName = "Carol";
			c182.LastName = "Foster";
			c182.Gender = "Female";
			c182.Email = "cfoster51@ucla.edu";
			c182.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Once");
			c182.ReferredFrom = "google.com.au";
			c182.AverageSale = 554.32m;
			db.Customers.AddOrUpdate(c => c.Email, c182);
			db.SaveChanges();

			Customer c183 = new Customer();
			c183.FirstName = "Ralph";
			c183.LastName = "Alvarez";
			c183.Gender = "Male";
			c183.Email = "ralvarez52@senate.gov";
			c183.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Never");
			c183.ReferredFrom = "ehow.com";
			c183.AverageSale = 438.22m;
			db.Customers.AddOrUpdate(c => c.Email, c183);
			db.SaveChanges();

			Customer c184 = new Customer();
			c184.FirstName = "Christina";
			c184.LastName = "Marshall";
			c184.Gender = "Female";
			c184.Email = "cmarshall53@senate.gov";
			c184.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Once");
			c184.ReferredFrom = "comcast.net";
			c184.AverageSale = 431.89m;
			db.Customers.AddOrUpdate(c => c.Email, c184);
			db.SaveChanges();

			Customer c185 = new Customer();
			c185.FirstName = "Phyllis";
			c185.LastName = "Schmidt";
			c185.Gender = "Female";
			c185.Email = "pschmidt54@clickbank.net";
			c185.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Monthly");
			c185.ReferredFrom = "reference.com";
			c185.AverageSale = 475.65m;
			db.Customers.AddOrUpdate(c => c.Email, c185);
			db.SaveChanges();

			Customer c186 = new Customer();
			c186.FirstName = "Fred";
			c186.LastName = "Ramirez";
			c186.Gender = "Male";
			c186.Email = "framirez55@disqus.com";
			c186.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Often");
			c186.ReferredFrom = "amazon.com";
			c186.AverageSale = 363.16m;
			db.Customers.AddOrUpdate(c => c.Email, c186);
			db.SaveChanges();

			Customer c187 = new Customer();
			c187.FirstName = "Anne";
			c187.LastName = "Peterson";
			c187.Gender = "Female";
			c187.Email = "apeterson56@ucla.edu";
			c187.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Often");
			c187.ReferredFrom = "google.fr";
			c187.AverageSale = 446.18m;
			db.Customers.AddOrUpdate(c => c.Email, c187);
			db.SaveChanges();

			Customer c188 = new Customer();
			c188.FirstName = "Chris";
			c188.LastName = "Chapman";
			c188.Gender = "Male";
			c188.Email = "cchapman57@privacy.gov.au";
			c188.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Often");
			c188.ReferredFrom = "youku.com";
			c188.AverageSale = 488.03m;
			db.Customers.AddOrUpdate(c => c.Email, c188);
			db.SaveChanges();

			Customer c189 = new Customer();
			c189.FirstName = "Christina";
			c189.LastName = "Hicks";
			c189.Gender = "Female";
			c189.Email = "chicks58@house.gov";
			c189.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Yearly");
			c189.ReferredFrom = "e-recht24.de";
			c189.AverageSale = 592.13m;
			db.Customers.AddOrUpdate(c => c.Email, c189);
			db.SaveChanges();

			Customer c190 = new Customer();
			c190.FirstName = "Ruth";
			c190.LastName = "Chapman";
			c190.Gender = "Female";
			c190.Email = "rchapman59@google.co.jp";
			c190.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Monthly");
			c190.ReferredFrom = "time.com";
			c190.AverageSale = 308.83m;
			db.Customers.AddOrUpdate(c => c.Email, c190);
			db.SaveChanges();

			Customer c191 = new Customer();
			c191.FirstName = "Pamela";
			c191.LastName = "Nelson";
			c191.Gender = "Female";
			c191.Email = "pnelson5a@hatena.ne.jp";
			c191.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Often");
			c191.ReferredFrom = "newsvine.com";
			c191.AverageSale = 447.04m;
			db.Customers.AddOrUpdate(c => c.Email, c191);
			db.SaveChanges();

			Customer c192 = new Customer();
			c192.FirstName = "Jack";
			c192.LastName = "King";
			c192.Gender = "Male";
			c192.Email = "jking5b@4shared.com";
			c192.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Yearly");
			c192.ReferredFrom = "cnn.com";
			c192.AverageSale = 513.64m;
			db.Customers.AddOrUpdate(c => c.Email, c192);
			db.SaveChanges();

			Customer c193 = new Customer();
			c193.FirstName = "Frances";
			c193.LastName = "Morales";
			c193.Gender = "Female";
			c193.Email = "fmorales5c@answers.com";
			c193.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Monthly");
			c193.ReferredFrom = "tripod.com";
			c193.AverageSale = 449.22m;
			db.Customers.AddOrUpdate(c => c.Email, c193);
			db.SaveChanges();

			Customer c194 = new Customer();
			c194.FirstName = "Doris";
			c194.LastName = "Hunt";
			c194.Gender = "Female";
			c194.Email = "dhunt5d@geocities.com";
			c194.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Once");
			c194.ReferredFrom = "earthlink.net";
			c194.AverageSale = 520.89m;
			db.Customers.AddOrUpdate(c => c.Email, c194);
			db.SaveChanges();

			Customer c195 = new Customer();
			c195.FirstName = "Chris";
			c195.LastName = "Medina";
			c195.Gender = "Male";
			c195.Email = "cmedina5e@altervista.org";
			c195.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Often");
			c195.ReferredFrom = "jugem.jp";
			c195.AverageSale = 419.89m;
			db.Customers.AddOrUpdate(c => c.Email, c195);
			db.SaveChanges();

			Customer c196 = new Customer();
			c196.FirstName = "Jonathan";
			c196.LastName = "Parker";
			c196.Gender = "Male";
			c196.Email = "jparker5f@imdb.com";
			c196.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Often");
			c196.ReferredFrom = "go.com";
			c196.AverageSale = 537.97m;
			db.Customers.AddOrUpdate(c => c.Email, c196);
			db.SaveChanges();

			Customer c197 = new Customer();
			c197.FirstName = "Carol";
			c197.LastName = "Banks";
			c197.Gender = "Female";
			c197.Email = "cbanks5g@ca.gov";
			c197.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Seldom");
			c197.ReferredFrom = "mediafire.com";
			c197.AverageSale = 465.87m;
			db.Customers.AddOrUpdate(c => c.Email, c197);
			db.SaveChanges();

			Customer c198 = new Customer();
			c198.FirstName = "Mary";
			c198.LastName = "Gonzalez";
			c198.Gender = "Female";
			c198.Email = "mgonzalez5h@gov.uk";
			c198.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Once");
			c198.ReferredFrom = "skype.com";
			c198.AverageSale = 249.09m;
			db.Customers.AddOrUpdate(c => c.Email, c198);
			db.SaveChanges();

			Customer c199 = new Customer();
			c199.FirstName = "Linda";
			c199.LastName = "Collins";
			c199.Gender = "Female";
			c199.Email = "lcollins5i@dailymail.co.uk";
			c199.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Once");
			c199.ReferredFrom = "sourceforge.net";
			c199.AverageSale = 525.27m;
			db.Customers.AddOrUpdate(c => c.Email, c199);
			db.SaveChanges();

			Customer c200 = new Customer();
			c200.FirstName = "James";
			c200.LastName = "Snyder";
			c200.Gender = "Male";
			c200.Email = "jsnyder5j@go.com";
			c200.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Seldom");
			c200.ReferredFrom = "latimes.com";
			c200.AverageSale = 484.14m;
			db.Customers.AddOrUpdate(c => c.Email, c200);
			db.SaveChanges();

			Customer c201 = new Customer();
			c201.FirstName = "Jean";
			c201.LastName = "Howell";
			c201.Gender = "Female";
			c201.Email = "jhowell5k@rambler.ru";
			c201.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Monthly");
			c201.ReferredFrom = "vistaprint.com";
			c201.AverageSale = 416.77m;
			db.Customers.AddOrUpdate(c => c.Email, c201);
			db.SaveChanges();

			Customer c202 = new Customer();
			c202.FirstName = "Sara";
			c202.LastName = "Thomas";
			c202.Gender = "Female";
			c202.Email = "sthomas5l@goo.gl";
			c202.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Never");
			c202.ReferredFrom = "narod.ru";
			c202.AverageSale = 458.14m;
			db.Customers.AddOrUpdate(c => c.Email, c202);
			db.SaveChanges();

			Customer c203 = new Customer();
			c203.FirstName = "Julie";
			c203.LastName = "Adams";
			c203.Gender = "Female";
			c203.Email = "jadams5m@tripadvisor.com";
			c203.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Seldom");
			c203.ReferredFrom = "washingtonpost.com";
			c203.AverageSale = 459.96m;
			db.Customers.AddOrUpdate(c => c.Email, c203);
			db.SaveChanges();

			Customer c204 = new Customer();
			c204.FirstName = "Scott";
			c204.LastName = "Simmons";
			c204.Gender = "Male";
			c204.Email = "ssimmons5n@goo.gl";
			c204.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Never");
			c204.ReferredFrom = "cam.ac.uk";
			c204.AverageSale = 318.09m;
			db.Customers.AddOrUpdate(c => c.Email, c204);
			db.SaveChanges();

			Customer c205 = new Customer();
			c205.FirstName = "Justin";
			c205.LastName = "Franklin";
			c205.Gender = "Male";
			c205.Email = "jfranklin5o@plala.or.jp";
			c205.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Once");
			c205.ReferredFrom = "instagram.com";
			c205.AverageSale = 532.75m;
			db.Customers.AddOrUpdate(c => c.Email, c205);
			db.SaveChanges();

			Customer c206 = new Customer();
			c206.FirstName = "Ann";
			c206.LastName = "Nguyen";
			c206.Gender = "Female";
			c206.Email = "anguyen5p@rambler.ru";
			c206.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Never");
			c206.ReferredFrom = "skyrock.com";
			c206.AverageSale = 323.55m;
			db.Customers.AddOrUpdate(c => c.Email, c206);
			db.SaveChanges();

			Customer c207 = new Customer();
			c207.FirstName = "Jimmy";
			c207.LastName = "Gilbert";
			c207.Gender = "Male";
			c207.Email = "jgilbert5q@wix.com";
			c207.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Never");
			c207.ReferredFrom = "fastcompany.com";
			c207.AverageSale = 367.5m;
			db.Customers.AddOrUpdate(c => c.Email, c207);
			db.SaveChanges();

			Customer c208 = new Customer();
			c208.FirstName = "Julie";
			c208.LastName = "Stanley";
			c208.Gender = "Female";
			c208.Email = "jstanley5r@phoca.cz";
			c208.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Monthly");
			c208.ReferredFrom = "myspace.com";
			c208.AverageSale = 325.69m;
			db.Customers.AddOrUpdate(c => c.Email, c208);
			db.SaveChanges();

			Customer c209 = new Customer();
			c209.FirstName = "Janet";
			c209.LastName = "Bradley";
			c209.Gender = "Female";
			c209.Email = "jbradley5s@berkeley.edu";
			c209.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Yearly");
			c209.ReferredFrom = "youtube.com";
			c209.AverageSale = 398.41m;
			db.Customers.AddOrUpdate(c => c.Email, c209);
			db.SaveChanges();

			Customer c210 = new Customer();
			c210.FirstName = "Linda";
			c210.LastName = "Cooper";
			c210.Gender = "Female";
			c210.Email = "lcooper5t@businesswire.com";
			c210.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Once");
			c210.ReferredFrom = "163.com";
			c210.AverageSale = 547.75m;
			db.Customers.AddOrUpdate(c => c.Email, c210);
			db.SaveChanges();

			Customer c211 = new Customer();
			c211.FirstName = "Christopher";
			c211.LastName = "Martinez";
			c211.Gender = "Male";
			c211.Email = "cmartinez5u@gov.uk";
			c211.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Seldom");
			c211.ReferredFrom = "epa.gov";
			c211.AverageSale = 468.9m;
			db.Customers.AddOrUpdate(c => c.Email, c211);
			db.SaveChanges();

			Customer c212 = new Customer();
			c212.FirstName = "Anna";
			c212.LastName = "Ross";
			c212.Gender = "Female";
			c212.Email = "aross5v@japanpost.jp";
			c212.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Yearly");
			c212.ReferredFrom = "deviantart.com";
			c212.AverageSale = 449.74m;
			db.Customers.AddOrUpdate(c => c.Email, c212);
			db.SaveChanges();

			Customer c213 = new Customer();
			c213.FirstName = "David";
			c213.LastName = "Miller";
			c213.Gender = "Male";
			c213.Email = "dmiller5w@ibm.com";
			c213.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Often");
			c213.ReferredFrom = "list-manage.com";
			c213.AverageSale = 382.52m;
			db.Customers.AddOrUpdate(c => c.Email, c213);
			db.SaveChanges();

			Customer c214 = new Customer();
			c214.FirstName = "Jack";
			c214.LastName = "Nguyen";
			c214.Gender = "Male";
			c214.Email = "jnguyen5x@51.la";
			c214.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Never");
			c214.ReferredFrom = "reverbnation.com";
			c214.AverageSale = 494.78m;
			db.Customers.AddOrUpdate(c => c.Email, c214);
			db.SaveChanges();

			Customer c215 = new Customer();
			c215.FirstName = "Eric";
			c215.LastName = "Burke";
			c215.Gender = "Male";
			c215.Email = "eburke5y@tripod.com";
			c215.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Monthly");
			c215.ReferredFrom = "hibu.com";
			c215.AverageSale = 500m;
			db.Customers.AddOrUpdate(c => c.Email, c215);
			db.SaveChanges();

			Customer c216 = new Customer();
			c216.FirstName = "Kevin";
			c216.LastName = "Nelson";
			c216.Gender = "Male";
			c216.Email = "knelson5z@home.pl";
			c216.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Never");
			c216.ReferredFrom = "kickstarter.com";
			c216.AverageSale = 262.42m;
			db.Customers.AddOrUpdate(c => c.Email, c216);
			db.SaveChanges();

			Customer c217 = new Customer();
			c217.FirstName = "William";
			c217.LastName = "Ortiz";
			c217.Gender = "Male";
			c217.Email = "wortiz60@technorati.com";
			c217.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Monthly");
			c217.ReferredFrom = "rambler.ru";
			c217.AverageSale = 467.34m;
			db.Customers.AddOrUpdate(c => c.Email, c217);
			db.SaveChanges();

			Customer c218 = new Customer();
			c218.FirstName = "Kimberly";
			c218.LastName = "Barnes";
			c218.Gender = "Female";
			c218.Email = "kbarnes61@storify.com";
			c218.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Weekly");
			c218.ReferredFrom = "mediafire.com";
			c218.AverageSale = 361.07m;
			db.Customers.AddOrUpdate(c => c.Email, c218);
			db.SaveChanges();

			Customer c219 = new Customer();
			c219.FirstName = "Carlos";
			c219.LastName = "Russell";
			c219.Gender = "Male";
			c219.Email = "crussell62@spotify.com";
			c219.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Yearly");
			c219.ReferredFrom = "soundcloud.com";
			c219.AverageSale = 427.13m;
			db.Customers.AddOrUpdate(c => c.Email, c219);
			db.SaveChanges();

			Customer c220 = new Customer();
			c220.FirstName = "Marie";
			c220.LastName = "Green";
			c220.Gender = "Female";
			c220.Email = "mgreen63@weibo.com";
			c220.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Daily");
			c220.ReferredFrom = "hexun.com";
			c220.AverageSale = 471.54m;
			db.Customers.AddOrUpdate(c => c.Email, c220);
			db.SaveChanges();

			Customer c221 = new Customer();
			c221.FirstName = "Kathryn";
			c221.LastName = "Ray";
			c221.Gender = "Female";
			c221.Email = "kray64@sbwire.com";
			c221.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Never");
			c221.ReferredFrom = "mashable.com";
			c221.AverageSale = 115.16m;
			db.Customers.AddOrUpdate(c => c.Email, c221);
			db.SaveChanges();

			Customer c222 = new Customer();
			c222.FirstName = "Dorothy";
			c222.LastName = "Adams";
			c222.Gender = "Female";
			c222.Email = "dadams65@bloglines.com";
			c222.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Once");
			c222.ReferredFrom = "wikia.com";
			c222.AverageSale = 423.32m;
			db.Customers.AddOrUpdate(c => c.Email, c222);
			db.SaveChanges();

			Customer c223 = new Customer();
			c223.FirstName = "John";
			c223.LastName = "Ruiz";
			c223.Gender = "Male";
			c223.Email = "jruiz66@goo.ne.jp";
			c223.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Daily");
			c223.ReferredFrom = "bluehost.com";
			c223.AverageSale = 544.2m;
			db.Customers.AddOrUpdate(c => c.Email, c223);
			db.SaveChanges();

			Customer c224 = new Customer();
			c224.FirstName = "Martha";
			c224.LastName = "Jenkins";
			c224.Gender = "Female";
			c224.Email = "mjenkins67@github.com";
			c224.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Daily");
			c224.ReferredFrom = "samsung.com";
			c224.AverageSale = 583.65m;
			db.Customers.AddOrUpdate(c => c.Email, c224);
			db.SaveChanges();

			Customer c225 = new Customer();
			c225.FirstName = "Phillip";
			c225.LastName = "Ward";
			c225.Gender = "Male";
			c225.Email = "pward68@icio.us";
			c225.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Daily");
			c225.ReferredFrom = "myspace.com";
			c225.AverageSale = 400.98m;
			db.Customers.AddOrUpdate(c => c.Email, c225);
			db.SaveChanges();

			Customer c226 = new Customer();
			c226.FirstName = "Alice";
			c226.LastName = "Ryan";
			c226.Gender = "Female";
			c226.Email = "aryan69@tiny.cc";
			c226.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Seldom");
			c226.ReferredFrom = "youtube.com";
			c226.AverageSale = 417.98m;
			db.Customers.AddOrUpdate(c => c.Email, c226);
			db.SaveChanges();

			Customer c227 = new Customer();
			c227.FirstName = "Norma";
			c227.LastName = "Carr";
			c227.Gender = "Female";
			c227.Email = "ncarr6a@addtoany.com";
			c227.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Monthly");
			c227.ReferredFrom = "tumblr.com";
			c227.AverageSale = 361m;
			db.Customers.AddOrUpdate(c => c.Email, c227);
			db.SaveChanges();

			Customer c228 = new Customer();
			c228.FirstName = "Amanda";
			c228.LastName = "Larson";
			c228.Gender = "Female";
			c228.Email = "alarson6b@census.gov";
			c228.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Daily");
			c228.ReferredFrom = "unc.edu";
			c228.AverageSale = 481.05m;
			db.Customers.AddOrUpdate(c => c.Email, c228);
			db.SaveChanges();

			Customer c229 = new Customer();
			c229.FirstName = "Wayne";
			c229.LastName = "Gardner";
			c229.Gender = "Male";
			c229.Email = "wgardner6c@slate.com";
			c229.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Once");
			c229.ReferredFrom = "virginia.edu";
			c229.AverageSale = 430.82m;
			db.Customers.AddOrUpdate(c => c.Email, c229);
			db.SaveChanges();

			Customer c230 = new Customer();
			c230.FirstName = "Evelyn";
			c230.LastName = "Williams";
			c230.Gender = "Female";
			c230.Email = "ewilliams6d@noaa.gov";
			c230.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Often");
			c230.ReferredFrom = "tiny.cc";
			c230.AverageSale = 526.57m;
			db.Customers.AddOrUpdate(c => c.Email, c230);
			db.SaveChanges();

			Customer c231 = new Customer();
			c231.FirstName = "Harry";
			c231.LastName = "Cruz";
			c231.Gender = "Male";
			c231.Email = "hcruz6e@wp.com";
			c231.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Daily");
			c231.ReferredFrom = "psu.edu";
			c231.AverageSale = 299.17m;
			db.Customers.AddOrUpdate(c => c.Email, c231);
			db.SaveChanges();

			Customer c232 = new Customer();
			c232.FirstName = "Brenda";
			c232.LastName = "Chapman";
			c232.Gender = "Female";
			c232.Email = "bchapman6f@accuweather.com";
			c232.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Weekly");
			c232.ReferredFrom = "mapy.cz";
			c232.AverageSale = 403.04m;
			db.Customers.AddOrUpdate(c => c.Email, c232);
			db.SaveChanges();

			Customer c233 = new Customer();
			c233.FirstName = "Rachel";
			c233.LastName = "Kelley";
			c233.Gender = "Female";
			c233.Email = "rkelley6g@rambler.ru";
			c233.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Yearly");
			c233.ReferredFrom = "samsung.com";
			c233.AverageSale = 472.5m;
			db.Customers.AddOrUpdate(c => c.Email, c233);
			db.SaveChanges();

			Customer c234 = new Customer();
			c234.FirstName = "Janice";
			c234.LastName = "Watkins";
			c234.Gender = "Female";
			c234.Email = "jwatkins6h@blogs.com";
			c234.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Never");
			c234.ReferredFrom = "google.it";
			c234.AverageSale = 316.49m;
			db.Customers.AddOrUpdate(c => c.Email, c234);
			db.SaveChanges();

			Customer c235 = new Customer();
			c235.FirstName = "Kenneth";
			c235.LastName = "Griffin";
			c235.Gender = "Male";
			c235.Email = "kgriffin6i@reverbnation.com";
			c235.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Once");
			c235.ReferredFrom = "mapquest.com";
			c235.AverageSale = 353.81m;
			db.Customers.AddOrUpdate(c => c.Email, c235);
			db.SaveChanges();

			Customer c236 = new Customer();
			c236.FirstName = "Shirley";
			c236.LastName = "Warren";
			c236.Gender = "Female";
			c236.Email = "swarren6j@hostgator.com";
			c236.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Often");
			c236.ReferredFrom = "springer.com";
			c236.AverageSale = 401.38m;
			db.Customers.AddOrUpdate(c => c.Email, c236);
			db.SaveChanges();

			Customer c237 = new Customer();
			c237.FirstName = "Dorothy";
			c237.LastName = "Moreno";
			c237.Gender = "Female";
			c237.Email = "dmoreno6k@wisc.edu";
			c237.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Often");
			c237.ReferredFrom = "diigo.com";
			c237.AverageSale = 346.02m;
			db.Customers.AddOrUpdate(c => c.Email, c237);
			db.SaveChanges();

			Customer c238 = new Customer();
			c238.FirstName = "Ashley";
			c238.LastName = "Thomas";
			c238.Gender = "Female";
			c238.Email = "athomas6l@google.de";
			c238.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Never");
			c238.ReferredFrom = "ehow.com";
			c238.AverageSale = 531.95m;
			db.Customers.AddOrUpdate(c => c.Email, c238);
			db.SaveChanges();

			Customer c239 = new Customer();
			c239.FirstName = "Scott";
			c239.LastName = "Perez";
			c239.Gender = "Male";
			c239.Email = "sperez6m@redcross.org";
			c239.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Daily");
			c239.ReferredFrom = "blogger.com";
			c239.AverageSale = 309.43m;
			db.Customers.AddOrUpdate(c => c.Email, c239);
			db.SaveChanges();

			Customer c240 = new Customer();
			c240.FirstName = "Rebecca";
			c240.LastName = "Palmer";
			c240.Gender = "Female";
			c240.Email = "rpalmer6n@slashdot.org";
			c240.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Yearly");
			c240.ReferredFrom = "usa.gov";
			c240.AverageSale = 488.93m;
			db.Customers.AddOrUpdate(c => c.Email, c240);
			db.SaveChanges();

			Customer c241 = new Customer();
			c241.FirstName = "Gary";
			c241.LastName = "Watson";
			c241.Gender = "Male";
			c241.Email = "gwatson6o@xing.com";
			c241.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Once");
			c241.ReferredFrom = "woothemes.com";
			c241.AverageSale = 359.54m;
			db.Customers.AddOrUpdate(c => c.Email, c241);
			db.SaveChanges();

			Customer c242 = new Customer();
			c242.FirstName = "Amanda";
			c242.LastName = "Barnes";
			c242.Gender = "Female";
			c242.Email = "abarnes6p@ftc.gov";
			c242.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Yearly");
			c242.ReferredFrom = "ebay.com";
			c242.AverageSale = 441.38m;
			db.Customers.AddOrUpdate(c => c.Email, c242);
			db.SaveChanges();

			Customer c243 = new Customer();
			c243.FirstName = "Louise";
			c243.LastName = "Knight";
			c243.Gender = "Female";
			c243.Email = "lknight6q@topsy.com";
			c243.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Monthly");
			c243.ReferredFrom = "answers.com";
			c243.AverageSale = 397.43m;
			db.Customers.AddOrUpdate(c => c.Email, c243);
			db.SaveChanges();

			Customer c244 = new Customer();
			c244.FirstName = "Ernest";
			c244.LastName = "Burke";
			c244.Gender = "Male";
			c244.Email = "eburke6r@springer.com";
			c244.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Once");
			c244.ReferredFrom = "cdbaby.com";
			c244.AverageSale = 322.17m;
			db.Customers.AddOrUpdate(c => c.Email, c244);
			db.SaveChanges();

			Customer c245 = new Customer();
			c245.FirstName = "Carolyn";
			c245.LastName = "Nichols";
			c245.Gender = "Female";
			c245.Email = "cnichols6s@geocities.jp";
			c245.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Once");
			c245.ReferredFrom = "blogs.com";
			c245.AverageSale = 377.66m;
			db.Customers.AddOrUpdate(c => c.Email, c245);
			db.SaveChanges();

			Customer c246 = new Customer();
			c246.FirstName = "Helen";
			c246.LastName = "Oliver";
			c246.Gender = "Female";
			c246.Email = "holiver6t@bluehost.com";
			c246.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Never");
			c246.ReferredFrom = "timesonline.co.uk";
			c246.AverageSale = 436.45m;
			db.Customers.AddOrUpdate(c => c.Email, c246);
			db.SaveChanges();

			Customer c247 = new Customer();
			c247.FirstName = "Johnny";
			c247.LastName = "Gutierrez";
			c247.Gender = "Male";
			c247.Email = "jgutierrez6u@thetimes.co.uk";
			c247.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Once");
			c247.ReferredFrom = "goodreads.com";
			c247.AverageSale = 550.66m;
			db.Customers.AddOrUpdate(c => c.Email, c247);
			db.SaveChanges();

			Customer c248 = new Customer();
			c248.FirstName = "Gregory";
			c248.LastName = "Walker";
			c248.Gender = "Male";
			c248.Email = "gwalker6v@hao123.com";
			c248.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Often");
			c248.ReferredFrom = "yelp.com";
			c248.AverageSale = 247.71m;
			db.Customers.AddOrUpdate(c => c.Email, c248);
			db.SaveChanges();

			Customer c249 = new Customer();
			c249.FirstName = "Jacqueline";
			c249.LastName = "Butler";
			c249.Gender = "Female";
			c249.Email = "jbutler6w@globo.com";
			c249.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Often");
			c249.ReferredFrom = "gravatar.com";
			c249.AverageSale = 141.96m;
			db.Customers.AddOrUpdate(c => c.Email, c249);
			db.SaveChanges();

			Customer c250 = new Customer();
			c250.FirstName = "Albert";
			c250.LastName = "Ford";
			c250.Gender = "Male";
			c250.Email = "aford6x@dell.com";
			c250.Frequency = db.Frequencies.FirstOrDefault(f => f.Name == "Seldom");
			c250.ReferredFrom = "wunderground.com";
			c250.AverageSale = 434.98m;
			db.Customers.AddOrUpdate(c => c.Email, c250);
			db.SaveChanges();

		}
	}
}
