// <auto-generated />
namespace Yeluru_Sai_HW7.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class SecondSetup : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SecondSetup));
        
        string IMigrationMetadata.Id
        {
            get { return "201611070522575_SecondSetup"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
